fifteen increment complitted
Aleksey-Andris/go-yandex-shortener pull request #16
Opened 2023-10-01 11:32 UTC by Aleksey-Andris

2023-10-01 11:43 UTC, Aleksey-Andris commented
Автотесты пройдены. Но не очень понятно, как эффективно организовать буффер. В примере из курса, канал вычитывается в локальный слайс метода, а этот метод запущен в горутине. Но в таком случае при остановке, мы можем потерять значения из слайса. Если делать слайс общим, тогда приходится ставить блокировки, что ограничивает возможности сервера. 
Также возникла проблема с юнитами. Не регистрируются вызовы моков, если они выполнены в отдельном потоке. А бокировки приводят к ошибкам при дебаге тестов.

2023-10-02 19:21 UTC, popoffvg requested changes

2023-10-02 19:21 UTC, popoffvg commented on internal/app/delivery/handlers/link.go
> +			h.identsBuf = nil
[minor]

Лучше переиспользовать уже аллоцированную память через `h.identsBuf = h.identsBuf[:0]`

2023-10-02 19:21 UTC, popoffvg commented on internal/app/delivery/handlers/handler.go
> +		delChan:      make(chan delMesage, 1024),
[major]

Такой буфер у канала не обоснован. Если мы не справляемся с нагрузкой, то буфер не поможет. Если справляемся и краткосрочный пик, то лучше в текущем решении немного подождать.

2023-10-02 19:21 UTC, popoffvg commented on internal/app/delivery/handlers/link.go
> +			h.Lock()
[major]

В этот момент блокировка может быть захвачена при завершении работы сервера, а сообщение мы уже вычитали. Лучше обрабатывать все события в одном месте, гарантирую что данные из канала не будут потеряны и не нужен будет мьютекс.

2023-10-06 14:19 UTC, merged